### ISSUE TITLE
Error on Login Page

### ISSUE THREAD

**Issue by ricky9818** [norictech/ci-inventory-management-system#1]
Hi,

I downloaded this application, however when I try to run it show an error as below : 

Not Found

The requested URL /ci-ims/action/login was not found on this server.

Please help how to solve this problem.

**Comment by adwikaa** [comment]
i m also getting same issue

**Comment by ricky9818** [comment]
I have found the way to solve this problem.
create an .htaccess file on root folder and type in the following inside 👍 
#RewriteEngine on
#RewriteCond $1 !^(index\.php|images|robots\.txt)
#RewriteRule ^(.*)$ /index.php/$1 [L]
RewriteEngine on
RewriteCond $1 !^(index\.php|resources|robots\.txt)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L,QSA]

Hope that this help.
